### ISSUE TITLE
rstan crashes R (and RStudio) when generated quantities contain array of large matrices

### ISSUE THREAD

**Issue by lutzgruber** [stan-dev/rstan#464]
#### Summary:
rstan crashes R (and RStudio) when the generated quantities block contains an array of large matrices, for example, `matrix[5000, 5] testobject[50]`.

#### Description:
Main problem: The R session crashes and takes down RStudio with it when the generated quantities block of a stan model contains an array of large matrices, for example `matrix[5000, 5] testobject[50]`.

Additional notes: The model runs fine for arrays of very small matrices, for example, `matrix[50, 5] testobject[50]`, in which case the rstan function call completes in about 2 seconds. The model does not crash for arrays of medium size matrices, for example, `matrix[500, 5] testobject[50]`, but takes disproportionally longer to complete (about 380 seconds).

This crash is likely not caused by a lack of available memory, given that there were more than 64GB of free memory at the time of the crash and memory usage of the R session only went up to 0.7GB by the time the crash occurred.

#### Reproducible Steps:

```
library(Rcpp)

test_model = rstan::stan_model(
    model_code = "data {
      int nrow;
      int ncol;
      int nmatrices;
    }
    generated quantities {
      matrix[nrow, ncol] testobject[nmatrices];

      for (i in 1:nmatrices) {
        testobject[i] = rep_matrix(0.0 + i, nrow, ncol);
      }
    }"
)

# takes about 2 seconds
system.time({
test_result1 = rstan::sampling(
    object = test_model,
    algorithm = "Fixed_param",
    chains = 1,
    iter = 1,
    verbose = TRUE,
    data = list(nrow = 50, ncol = 5, nmatrices = 50)
)
})

# takes about 380 seconds
system.time({
test_result2 = rstan::sampling(
    object = test_model,
    algorithm = "Fixed_param",
    chains = 1,
    iter = 1,
    verbose = TRUE,
    data = list(nrow = 500, ncol = 5, nmatrices = 50)
)
})

# crash
system.time({
test_result3 = rstan::sampling(
    object = test_model,
    algorithm = "Fixed_param",
    chains = 1,
    iter = 1,
    verbose = TRUE,
    data = list(nrow = 5000, ncol = 5, nmatrices = 50)
)
})
```

#### Current Output:
Crashed R/RStudio session

#### Expected Output:
No crash for arrays of large matrices; shorter runtime for array of medium size matrices. Any help is appreciated!

#### RStan Version:
2.16.2

#### R Version:
R version 3.4.2 (2017-09-28)

#### Operating System:
Windows Server 2016

**Comment by bob-carpenter** [comment]
Each saved value requires 8 bytes.  5 x 50 x 5000 = 1,250,000, so you need 10MB/iteration just for that data structure.  RStan defaults to 8000 iterations and saves warmup, so you'd need 80 GB or so just for storage and I believe another equal amount for a copy.

I don't know if there's a way to catch the memory allocation and have it fail gracefully rather than crash.  I agree that crashing R is a bad idea.

**Comment by lutzgruber** [comment]
Does RStan still default to 8000 iterations even when I set `iter = 1`?

**Comment by bob-carpenter** [comment]
Sorry---missed that.  It should use the number of iterations specified.  No idea why this is causing a problem for you.

**Comment by sakrejda** [comment]
This might be an R thing that bit us before.  I'll try to reproduce tonight
with a debugger if nobody else gets to it.

**Comment by lutzgruber** [comment]
Thank you both for your comments. @sakrejda, could you reproduce this problem?

**Comment by bgoodri** [comment]
Yeah, I think this has to do with the recursive `std::vector<std::vector<...>>` way in which stuff gets stored in RStan. We need to be allocating a contiguous block of memory once. Unfortunately, this may not get fixed until RStan3. You can currently do `pars = ""`, specify `sample_file`, and read the samples from the csv files (slowly).

**Comment by sakrejda** [comment]
What crashes for you runs fine for me, I just ran a bigger version to see if it would reproduce the problem.

**Comment by lutzgruber** [comment]
Ok, thanks for checking! 

@bgoodri how would specifying a `sample_file` help me here? I was trying to export an array of matrices from stan into R, not import it from R into my stan program.

**Comment by bgoodri** [comment]
The `sample_file` argument tells Stan where to write the CSV file with all
the parameter draws to. If you also do `pars = ""`, then you will likely
avoid the bug you encountered.

**Comment by lutzgruber** [comment]
That sounds very helpful. I will give it a try. Thank you!

**Comment by sakrejda** [comment]
From a backtrace, this is caused by the destructor of rstan's writer (I think there's an underlying Rcpp bug but I don't understand it yet).  @bgoodri I think if rstan used an internal representation that was matrix or a single vector we coudl fix this bug...  Is there a lot of code that assumes the `std::vector<std::vector<...>>` structure?  This wouldn't be complicated to fix.  I guess we could also just implement a more careful destructor than the default.

I guess I'm not sure why this needs to wait for Stan 3.  Do you just not have the time to deal with it or are there deeper issues?

**Comment by sakrejda** [comment]
Also... I can't figure out where `InternalVector` is coming from.  What is it?

**Comment by bgoodri** [comment]
It is not exactly easy, but the reason I was saying that it would likely have to wait for rstan3 is that it breaks backward compatibility with whatever might be relying on the list-of-lists storeage that RStan does currently.

**Comment by sakrejda** [comment]
You mean outside packages?

**Comment by bgoodri** [comment]
Yeah

**Comment by sakrejda** [comment]
I'll see if I can write an alternative destructor. I'm not sure why this is
happening so it may takes a while.

**Comment by maverickg** [comment]
Is this actually similar to https://github.com/stan-dev/rstan/issues/121 ?

**Comment by sakrejda** [comment]
This at some point triggers `R_ReleaseObject` which, depending on the c++ std library used, either pops elements off the end of a length N list or recurses through the entire list in order to pop off each element.... so we're using Rcpp correctly, which uses R correctly, but R for some reason uses a sometimes-recursive destructor for lists.  I've seen this on R-devel before and the answer seemed to be "meh".  I've never been able to reproduce this in R itself using nested lists so the gc may do something different that doesn't have this problem.  We could 1) allocate the list on the R side and just wrap it using Rcpp, then the memory structure should be the same but destruction would be handled by R; 2) it sounds like order of destruction of std::vector elements is the problem here so I suppose we could write a standard allocator (I haven't done it... not sure I'll have time to figure it out before Stan3...); or 3) we could let it leak.  I think option #\1 is the best/easiest and most reliable.  I think it would just entail re-writing the writer to gets its memory structure passed in via the constructor.

**Comment by sakrejda** [comment]
Relevant part of backtrace follows, it's triggered at line 560 of stan_fit.hpp by the auto_ptr reset.  I'm a little confused why the backtrace points there since the destructor isn't called till the next reset or end of scope but maybe that's just a formality.

```
#520214 0x00007ffff78efd58 in RecursiveRelease (object=object@entry=0x55555b0ba3f8, list=0x5555773347f0)
    at memory.c:3296
#520215 0x00007ffff78efd58 in RecursiveRelease (object=object@entry=0x55555b0ba3f8, list=0x5555773347b8)
    at memory.c:3296
#520216 0x00007ffff78efd58 in RecursiveRelease (object=object@entry=0x55555b0ba3f8, list=0x555577334780)
    at memory.c:3296
#520217 0x00007ffff78efd58 in RecursiveRelease (object=object@entry=0x55555b0ba3f8, list=0x555577334748)
    at memory.c:3296
#520218 0x00007ffff78efd58 in RecursiveRelease (object=object@entry=0x55555b0ba3f8, list=0x555577334710)
    at memory.c:3296
#520219 0x00007ffff78f06d0 in R_ReleaseObject (object=0x55555b0ba3f8) at memory.c:3303
    rho=0x55555a0c7f90) at eval.c:2197
#520219 0x00007ffff78f06d0 in R_ReleaseObject (object=0x55555b0ba3f8) at memory.c:3303
#520220 0x00007ffff075ff5e in Rcpp::Rcpp_ReleaseObject (x=<optimized out>)
    at /home/krzysztofsR/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/RcppCommon.h:93
#520221 Rcpp::PreserveStorage<Rcpp::Vector<14, Rcpp::PreserveStorage> >::~PreserveStorage (
    this=<optimized out>, __in_chrg=<optimized out>)
    at /home/krzysztof/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp/storage/PreserveStorage.h:13
#520222 Rcpp::Vector<14, Rcpp::PreserveStorage>::~Vector (this=<optimized out>,
    __in_chrg=<optimized out>)
    at /home/krzysztof/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include/Rcpp/vector/Vector.h:30
#520223 std::_Destroy<Rcpp::Vector<14, Rcpp::PreserveStorage> > (__pointer=<optimized out>)
    at /usr/include/c++/6/bits/stl_construct.h:93
#520224 std::_Destroy_aux<false>::__destroy<Rcpp::Vector<14, Rcpp::PreserveStorage>*> (
    __last=<optimized out>, __first=0x55556af69c20) at /usr/include/c++/6/bits/stl_construct.h:103
#520225 std::_Destroy<Rcpp::Vector<14, Rcpp::PreserveStorage>*> (__last=<optimized out>,
    __first=<optimized out>) at /usr/include/c++/6/bits/stl_construct.h:126
#520226 std::_Destroy<Rcpp::Vector<14, Rcpp::PreserveStorage>*, Rcpp::Vector<14, Rcpp::PreserveStorage> >
#520227 std::vector<Rcpp::Vector<14, Rcpp::PreserveStorage>, std::allocator<Rcpp::Vector<14, Rcpp::Preser
    at /usr/include/c++/6/bits/stl_vector.h:426
#520228 rstan::values<Rcpp::Vector<14, Rcpp::PreserveStorage> >::~values (this=0x7ffffffef488,
    __in_chrg=<optimized out>)
    at /home/krzysztof/R/x86_64-pc-linux-gnu-library/3.3/rstan/include/rstan/values.hpp:13
#520229 rstan::filtered_values<Rcpp::Vector<14, Rcpp::PreserveStorage> >::~filtered_values (
    this=0x7ffffffef450, __in_chrg=<optimized out>)
    at /home/krzysztof/R/x86_64-pc-linux-gnu-library/3.3/rstan/include/rstan/filtered_values.hpp:13
#520230 0x00007ffff075ba15 in rstan::sample_writer_factory (
    csv_fstream=csv_fstream@entry=0x7fffffff0bc0, comment_stream=..., prefix="# ",
    N_sample_names=N_sample_names@entry=2, N_sampler_names=N_sampler_names@entry=0,
    N_constrained_param_names=<optimized out>, N_iter_save=1, warmup=0,
    qoi_idx=std::vector of length 1250001, capacity 2097152 = {...})
    at /home/krzysztof/R/x86_64-pc-linux-gnu-library/3.3/rstan/include/rstan/rstan_writer.hpp:116
#520231 0x00007ffff07d4002 in rstan::(anonymous namespace)::command<model6ad42c660a63_bf0781aa2c33c1eb421
    holder=..., qoi_idx=std::vector of length 1250001, capacity 2097152 = {...},
    fnames_oi=std::vector of length 1250001, capacity 2500000 = {...}, base_rng=...,
    this=<optimized out>, this=<optimized out>, this=<optimized out>, this=<optimized out>)
    at /home/krzysztof/R/x86_64-pc-linux-gnu-library/3.3/rstan/include/rstan/stan_fit.hpp:560
#520232 0x00007ffff07d65a0 in rstan::stan_fit<model6ad42c660a63_bf0781aa2c33c1eb4216b3ec49935508_namespac
    args_=<optimized out>)
    at /home/krzysztof/R/x86_64-pc-linux-gnu-library/3.3/rstan/include/rstan/stan_fit.hpp:1196

```

**Comment by sakrejda** [comment]
I guess you can also control the order of destruction manually: https://github.com/tidyverse/dplyr/issues/1396

**Comment by pourzanj** [comment]
I just had this problem today. I'm glad this thread showed up on Google. The problem was indeed that my generated quantities were too taking up too much memory.
